### ISSUE TITLE
Ldap Configuration - Unknown user

### ISSUE THREAD

**Issue by campbell-m** [meeting-room-booking-system/mrbs-code#3492]
(Transferred from the general mailing list)

We run a OpenLdap server, PHP 7.2.5 and MRBS v 1.11.3 on SLES 12 SP5
I have $ldap_debug and $ldap_debug_attributes  set to true.

The error log of PHP is set to /var/log/php_errors.log. But there is 
stored no debug information.

LDAP Configuration config.inc.php :

~~~php
$auth["type"] = "ldap";
$ldap_host = "ldap://ldap-rzh.ofd-h.de";
$ldap_tls = true;
$ldap_base_dn = "ou=humans,ou=steuer,o=landesverwaltung niedersachsen,c=de";
$ldap_user_attrib = "uid";
$ldap_get_user_email = true;
$ldap_email_attrib = 'mail';
$ldap_name_attrib = 'cn';
~~~

**Comment by campbell-m** [comment]
If you are not getting any output in your PHP error log then you should check (a) that it is writable and (b) the setting in your php.ini file of `log_errors`.

If you are still not getting any output in the error file then you could always, temporarily, send the debug output to the browser by changing line 376 of lib/MRBS/Auth.php from

~~~php
    error_log(
~~~

to

~~~php
    echo(
~~~

**Comment by campbell-m** [comment]
You may find that you need to configure the following in your config.inc.php file:

~~~php
// If you need to search the directory to find the user's DN to bind
// with, set the following to the attribute that holds the user's
// "username". In Microsoft AD directories this is "sAMAccountName"
// This can be an array.
//$ldap_dn_search_attrib = "sAMAccountName";

// If you need to bind as a particular user to do the search described
// above, specify the DN and password in the variables below
// These two parameters can be arrays.
// $ldap_dn_search_dn = "cn=Search User,ou=Users,dc=example,dc=com"; // Any compliant LDAP
// $ldap_dn_search_dn = "searchuser@example.com"; // A form which could work for AD LDAP
// $ldap_dn_search_password = "some-password";
~~~

**Comment by Bodo-von-Thadden** [comment]
I changed to permission of the log file, so it's now writeable by php.

`//$ldap_dn_search_attrib = "sAMAccountName";

// If you need to bind as a particular user to do the search described
// above, specify the DN and password in the variables below
// These two parameters can be arrays.
// $ldap_dn_search_dn = "cn=Search User,ou=Users,dc=example,dc=com"; // Any compliant LDAP
// $ldap_dn_search_dn = "searchuser@example.com"; // A form which could work for AD LDAP
// $ldap_dn_search_password = "some-password";
`

We only use OpenLdap for login with FreeRadius , not Microsoft AD

**Comment by campbell-m** [comment]
So now your log file is writeable, what does the debug information say?

**Comment by campbell-m** [comment]
> We only use OpenLdap for login with FreeRadius , not Microsoft AD

The settings are applicable to all types of LDAP, not just AD.

**Comment by Bodo-von-Thadden** [comment]
> So now your log file is writeable, what does the debug information say?

In the log file it say's :
`[23-Aug-2023 07:56:52 UTC] [MRBS DEBUG] MRBS\Auth\AuthLdap->action(730): got LDAP connection using ldap://ldap-rzh.ofd-h.de:389
[23-Aug-2023 07:56:52 UTC] [MRBS DEBUG] MRBS\Auth\AuthLdap->action(794): constructed dn 'uid=bodo-von.thadden@iuk.lst.niedersachsen.de,ou=humans,ou=steuer,o=landesverwaltung niedersachsen,c=de' and user_search 'uid=bodo-von.thadden@iuk.lst.niedersachsen.de' using 'uid'
[23-Aug-2023 07:56:52 UTC] [MRBS DEBUG] MRBS\Auth\AuthLdap::validateUserCallback(247): base_dn 'ou=humans,ou=steuer,o=landesverwaltung niedersachsen,c=de' dn 'uid=bodo-von.thadden@iuk.lst.niedersachsen.de,ou=humans,ou=steuer,o=landesverwaltung niedersachsen,c=de' user 'bodo-von.thadden@iuk.lst.niedersachsen.de'
[23-Aug-2023 07:56:52 UTC] [MRBS DEBUG] MRBS\Auth\AuthLdap::validateUserCallback(319): bind to 'uid=bodo-von.thadden@iuk.lst.niedersachsen.de,ou=humans,ou=steuer,o=landesverwaltung niedersachsen,c=de' failed: Invalid credentials
[23-Aug-2023 07:56:52 UTC] PHP Notice:  Please check your config file. The setting $twentyfourhour_format is no longer used and whether a 12 or 24-hour clock is used is determined by the locale. See systemdefaults.inc.php for more details. in /srv/www/htdocs/mrbs/internalconfig.inc.php on line 178
`

But the credentials are correct.

**Comment by campbell-m** [comment]
Is the uid "bodo-von.thadden@iuk.lst.niedersachsen.de" or is it really "bodo-von.thadden" or indeed something else?  I wonder if you should either (a) login with "bodo-von.thadden" or (b) set `$ldap_user_attrib = "mail";`?

By the way, it looks like you have upgraded from an earlier version of MRBS.  If so, could you login OK before?

**Comment by Bodo-von-Thadden** [comment]
Yeah, i upgraded to the current version. The ldap connection hasn't worked before, only the login with the db settings has worked.
I tried both ( my e-mail adress and the name ). We have a working ldap connection with the tool confluence from Atlassian.com that we use here in the office. There i use only my name for login.

**Comment by campbell-m** [comment]
And what does the debug log show when you login with your username?

**Comment by Bodo-von-Thadden** [comment]
I had created a user admin1 with the password 1admin. In the debug log there is no information then when i login with this credentials, but with the db connection wit works fine.
[https://abload.de/img/roomejf98.png](url)

**Comment by campbell-m** [comment]
Yes, but what does the debug log show when MRBS is configured for LDAP and you login with your LDAP username that you use with confluence?

**Comment by Bodo-von-Thadden** [comment]
I have there no access to log file of confluence. With the ldap settings it shows the above information

**Comment by campbell-m** [comment]
I suspect that you got "invalid credentials" because you used your email address and not your username.  I'm hoping that if you use your username the bind will work, but you will not be able to login because you haven't yet specified the search details above.

**Comment by Bodo-von-Thadden** [comment]
Good morning,
 I found out that when i use the ldap conection test site from confluence, that i use there my e-mail adress. We have as ldap schema additional a group called gruppen ( see picture below )
 
 https://abload.de/img/ldap_schemam9ccn.jpg
 
 
 the debug log show :


[24-Aug-2023` 08:24:38 UTC] [MRBS DEBUG] MRBS\Auth\AuthLdap->action(730): got LDAP connection using ldap://ldap-rzh.ofd-h.de:389
[24-Aug-2023 08:24:38 UTC] [MRBS DEBUG] MRBS\Auth\AuthLdap->action(794): constructed dn 'uid=bodo-von.thadden@iuk.lst.niedersachsen.de,ou=gruppen,ou=humans,ou=steuer,o=landesverwaltung niedersachsen,c=de' and user_search 'uid=bodo-von.thadden@iuk.lst.niedersachsen.de' using 'uid'
[24-Aug-2023 08:24:38 UTC] [MRBS DEBUG] MRBS\Auth\AuthLdap::validateUserCallback(247): base_dn 'ou=gruppen,ou=humans,ou=steuer,o=landesverwaltung niedersachsen,c=de' dn 'uid=bodo-von.thadden@iuk.lst.niedersachsen.de,ou=gruppen,ou=humans,ou=steuer,o=landesverwaltung niedersachsen,c=de' user 'bodo-von.thadden@iuk.lst.niedersachsen.de'
[24-Aug-2023 08:24:38 UTC] [MRBS DEBUG] MRBS\Auth\AuthLdap::validateUserCallback(319): bind to 'uid=bodo-von.thadden@iuk.lst.niedersachsen.de,ou=gruppen,ou=humans,ou=steuer,o=landesverwaltung niedersachsen,c=de' failed: Invalid credentials`

This is the ldap settings in the systemdefaults.inc.php :

'$ldap_host = "ldap://ldap-rzh.ofd-h.de";
//$ldap_tls = true;
$ldap_base_dn = "ou=gruppen,ou=humans,ou=steuer,o=landesverwaltung niedersachsen,c=de";

// If you have a non-standard LDAP port, you can define it here.
// This can be an array.
//$ldap_port = 389;

// If you do not want to use LDAP v3, change the following to false.
// This can be an array.
$ldap_v3 = true;

// If you want to use TLS, change the following to true.
// This can be an array.
$ldap_tls = true;

// Support configuring a TLS client certificate/key from within MRBS.
// Requires PHP 7.1.0 or later
//$ldap_client_cert = 'path-to-cert.crt';
//$ldap_client_key = 'path-to-key.key';

// LDAP base distinguish name.
// This can be an array.
//$ldap_base_dn = "ou=organizationalunit,dc=example,dc=com";

// Attribute within the base dn that contains the username.
// In Microsoft AD directories this is "sAMAccountName".
// This can be an array.
$ldap_user_attrib = "uid";

// If you need to search the directory to find the user's DN to bind
// with, set the following to the attribute that holds the user's
// "username". In Microsoft AD directories this is "sAMAccountName"
// This can be an array.
//$ldap_dn_search_attrib = "sAMAccountName";

// If you need to bind as a particular user to do the search described
// above, specify the DN and password in the variables below
// These two parameters can be arrays.
//$ldap_dn_search_dn = "cn=Bodo von Thadden,ou=steuer,o=landesverwaltung niedersachsen,c=de"; // Any compliant LDAP
// $ldap_dn_search_dn = "cn=Search User,ou=Users,dc=example,dc=com"; // Any compliant LDAP
//$ldap_dn_search_dn = "bodo-von.thadden@iuk.lst.niedersachsen.de"; // A form which could work for AD LDAP
// $ldap_dn_search_dn = "searchuser@example.com"; // A form which could work for AD LDAP
// $ldap_dn_search_password = "some-password";

// 'auth_ldap' extra configuration for ldap configuration of who can use
// the system
// If it's set, the $ldap_filter will be used to determine whether a
// user will be granted access to MRBS
// This can be an array.
// An example for Microsoft AD:
//$ldap_filter = "memberof=cn=whater,ou=whatver,dc=example,dc=com";
//$ldap_filter = "memberof=cn=ou=steuer,o=landesverwaltung niedersachsen,c=de"";
// If you need to filter a user by the group a user is in with an LDAP
// directory which stores group membership in the group object
// (like OpenLDAP) then you need to search for the groups they are
// in. If you want to do this, define the following two variables, an
// an appropriate $ldap_filter. e.g.:
$ldap_filter_base_dn = "ou=gruppen,ou=humans,ou=steuer,o=landesverwaltung niedersachsen,c=de";
// $ldap_filter_base_dn = "ou=Groups,dc=example,dc=com";
$ldap_filter_user_attr = "memberuid";
// $ldap_filter = "cn=MRBS Users";

// If you need to disable client referrals, this should be set to true.
// Note: Active Directory for Windows 2003 forward requires this.
// $ldap_disable_referrals = true;

// LDAP option for dereferencing aliases
// LDAP_DEREF_NEVER = 0 - (default) aliases are never dereferenced.
// LDAP_DEREF_SEARCHING = 1 - aliases should be dereferenced during the search
//      but not when locating the base object of the search.
// LDAP_DEREF_FINDING = 2 - aliases should be dereferenced when locating the base object but not during the search.
// LDAP_DEREF_ALWAYS = 3 - aliases should be dereferenced always.
//$ldap_deref = LDAP_DEREF_ALWAYS;

// Set to true to tell MRBS to look up a user's email address in LDAP.
// Utilises $ldap_email_attrib below
$ldap_get_user_email = false;
// The LDAP attribute which holds a user's email address
// This can be an array.
$ldap_email_attrib = 'mail';
// The LDAP attribute which holds a user's name. Another common attribute
// to use (with Active Directory) is 'displayname'.
// This can be an array.
$ldap_name_attrib = 'cn';

// The DN of the LDAP group that MRBS admins must be in. If this is defined
// then the $auth["admin"] is not used.
// This can be an array.
// $ldap_admin_group_dn = 'cn=admins,ou=whoever,dc=example,dc=com';

// The LDAP attribute that holds group membership details. Used with
// $ldap_admin_group_dn, above.
// This can be an array.
$ldap_group_member_attrib = 'memberof';

// Set to true if you want MRBS to call ldap_unbind() between successive
// attempts to bind. Unbinding while still connected upsets some
// LDAP servers
$ldap_unbind_between_attempts = false;

// By default MRBS will suppress "invalid credentials" error messages when binding
// in order to avoid the log filling up with warning messages when a user enters
// an incorrect username/password combination.  Set this to FALSE if you want these
// errors to be logged, eg in order to be able spot brute force attack attempts.
$ldap_suppress_invalid_credentials = true;

// Output debugging information for LDAP actions
$ldap_debug = true;

// Output debugging information for LDAP actions and also attribute names and values.
// A higher level of debugging, useful for discovering attribute names.
$ldap_debug_attributes = true;
`

**Comment by campbell-m** [comment]
What's the debug output when you try and login with your username instead of your email address?

**Comment by Bodo-von-Thadden** [comment]
> What's the debug output when you try and login with your username instead of your email address?

`[24-Aug-2023 09:38:29 UTC] [MRBS DEBUG] MRBS\Auth\AuthLdap->action(730): got LDAP connection using ldap://ldap-rzh.ofd-h.de:389
[24-Aug-2023 09:38:29 UTC] [MRBS DEBUG] MRBS\Auth\AuthLdap->action(794): constructed dn '=Bodo von Thadden,ou=steuer,o=landesverwaltung niedersachsen,c=de' and user_search '=Bodo von Thadden' using ''
[24-Aug-2023 09:38:29 UTC] [MRBS DEBUG] MRBS\Auth\AuthLdap::validateUserCallback(247): base_dn 'ou=steuer,o=landesverwaltung niedersachsen,c=de' dn '=Bodo von Thadden,ou=steuer,o=landesverwaltung niedersachsen,c=de' user 'Bodo von Thadden'
[24-Aug-2023 11:38:29 Europe/Berlin]
E_USER_WARNING in /srv/www/htdocs/mrbss/lib/MRBS/Auth/AuthLdap.php at line 855
Invalid DN syntax
MRBS GET: Array
(
)
MRBS POST: Array
(
    [csrf_token] => cd45fc38e47f3a7f9f4d528e0baf9031a190e0ad7b3c020bb814102a09fc6bf2
    [target_url] => index.php
    [action] => SetName
    [username] => ****
    [password] => ****
)
MRBS SESSION: Array
(
    [last_page] => /mrbss/admin.php
    [this_page] => /mrbss/admin.php
    [csrf_token] => cd45fc38e47f3a7f9f4d528e0baf9031a190e0ad7b3c020bb814102a09fc6bf2
)


[24-Aug-2023 11:38:29 Europe/Berlin] [MRBS DEBUG] MRBS\Auth\AuthLdap::validateUserCallback(319): bind to '=Bodo von Thadden,ou=steuer,o=landesverwaltung niedersachsen,c=de' failed: Invalid DN syntax [invalid DN]
[24-Aug-2023 09:38:43 UTC] [MRBS DEBUG] MRBS\Auth\AuthLdap->action(730): got LDAP connection using ldap://ldap-rzh.ofd-h.de:389
[24-Aug-2023 09:38:43 UTC] [MRBS DEBUG] MRBS\Auth\AuthLdap->action(794): constructed dn '=bodo-von.thadden,ou=steuer,o=landesverwaltung niedersachsen,c=de' and user_search '=bodo-von.thadden' using ''
[24-Aug-2023 09:38:43 UTC] [MRBS DEBUG] MRBS\Auth\AuthLdap::validateUserCallback(247): base_dn 'ou=steuer,o=landesverwaltung niedersachsen,c=de' dn '=bodo-von.thadden,ou=steuer,o=landesverwaltung niedersachsen,c=de' user 'bodo-von.thadden'
[24-Aug-2023 11:38:43 Europe/Berlin]
E_USER_WARNING in /srv/www/htdocs/mrbss/lib/MRBS/Auth/AuthLdap.php at line 855
Invalid DN syntax
MRBS GET: Array
(
)
MRBS POST: Array
(
    [csrf_token] => cd45fc38e47f3a7f9f4d528e0baf9031a190e0ad7b3c020bb814102a09fc6bf2
    [target_url] => index.php
    [action] => SetName
    [username] => ****
    [password] => ****
)
MRBS SESSION: Array
(
    [last_page] => /mrbss/admin.php
    [this_page] => /mrbss/admin.php
    [csrf_token] => cd45fc38e47f3a7f9f4d528e0baf9031a190e0ad7b3c020bb814102a09fc6bf2
)


[24-Aug-2023 11:38:43 Europe/Berlin] [MRBS DEBUG] MRBS\Auth\AuthLdap::validateUserCallback(319): bind to '=bodo-von.thadden,ou=steuer,o=landesverwaltung niedersachsen,c=de' failed: Invalid DN syntax [invalid DN]
`

**Comment by campbell-m** [comment]
I mean your user id, rather than your display name. Something like "bodo-von.thadden".

**Comment by campbell-m** [comment]
The other thing to try is setting `$ldap_user_attrib = "mail";` and logging in with your email address.

**Comment by Bodo-von-Thadden** [comment]
Hi,
I have got it worked today. Thank you for your help

Bodo von Thadden
