### ISSUE TITLE
same user level cannot modify booking

### ISSUE THREAD

**Issue by antham1616** [meeting-room-booking-system/mrbs-code#3493]
The same user level cannot modify booking made

i.e
first user (user account) make a booking
second user (user account) only have the option to copy entry not edit
third user (Admin account) has full capability

**Comment by campbell-m** [comment]
That's the way MRBS is designed to work.  Could you explain the issue a bit more please?  Is it (a) that it's not behaving like that or (b) that you would like a different behaviour?

**Comment by antham1616** [comment]
oh ok, i thought they would be able to alter as per the help file?

Why can't I delete/alter a meeting?
In order to delete or alter a meeting, **you must be logged in as the same User level as the person that made the meeting** ie a user or admin. Contact one of the meeting room administrators to have it deleted or changed.

**Comment by campbell-m** [comment]
That must be a local change on your system.  The standard code says

~~~text
      In order to delete or alter a meeting, you must be logged in as the
      same person that made the meeting.  Contact one of the meeting room
      administrators or the person who initially made the meeting to
      have it deleted or changed.
~~~

**Comment by campbell-m** [comment]
You'd have to modify the function `getWritable()` in mrbs_auth.inc, replacing the code at the end that looks like this:

~~~php
  // Always allowed to modify your own stuff
  $mrbs_user = session()->getCurrentUser();
  if (isset($mrbs_user) && isset($creator) && (strcasecmp_locale($creator, $mrbs_user->username) === 0))
  {
    return true;
  }

  // Otherwise you have to be a (booking) admin for this room
  if (is_book_admin($rooms))
  {
    return true;
  }

  // Unauthorised access
  return false;
~~~

with something like

~~~php
  // Always allowed to modify your own stuff
  $mrbs_user = session()->getCurrentUser();
  if (isset($mrbs_user) && isset($creator) && (strcasecmp_locale($creator, $mrbs_user->username) === 0))
  {
    return true;
  }

  // Also allowed to modify other people's, provided they are not admins
  $creator_user = auth()->getUser($creator);
  if (isset($mrbs_user) && isset($creator_user) && ($creator_user->level < 2))
  {
    return true;
  }

  // Otherwise you have to be a (booking) admin for this room
  if (is_book_admin($rooms))
  {
    return true;
  }

  // Unauthorised access
  return false;
~~~

I haven't tested this though.

**Comment by campbell-m** [comment]
I have just edited the code in the post above.

**Comment by antham1616** [comment]
Brilliant yes that works great

thanks
