### ISSUE TITLE
confirmation on edit series

### ISSUE THREAD

**Issue by antham1616** [meeting-room-booking-system/mrbs-code#3503]
How do i enable the confirmation on edit series? in view_entry.php there is this but no confirmation is prompted? 

~~~php
if (empty($button_attributes['disabled']) &&
          isset($repeat_id) &&
          series_has_registrants($repeat_id))
      {
        $button_attributes['onclick'] = "return confirm('" . escape_js(get_vocab("confirm_edit_series")) . "');";
      }
      generate_button($params, $button_attributes);
      echo "</div>\n";
    }
    echo "</div>\n";
~~~

**Comment by antham1616** [comment]
dont worry noticed the series has registrants, removed and now prompts working, thanks anyway

**Comment by campbell-m** [comment]
The confirmation dialogue box only appears if somebody has registered for at least one event in the series.  The reason is that if ther edit involves a change in date or time then MRBS doesn't know which events to assign registrants to. If you change the time by five minutes it might be reasonably obvious, but say you had a booking for every Thursday which is changed to every Monday, should somebody who has registered for this Thursday be assigned to next or last Monday?
