### ISSUE TITLE
Enforce lowercase username?

### ISSUE THREAD

**Issue by embeh** [meeting-room-booking-system/mrbs-code#3507]
Where would I need to adjust the PHP code to force the login username to always be lowercase?
Apparently, the LDAP login method treats the name 'User' differently from the name 'user', so 'User' cannot log in (as it does not exist with capital U).

(we are currently running MRBS 1.8.0 but any pointer, even for the latest release, would be useful).

Thanks in advance!

**Comment by campbell-m** [comment]
In MRBS 1.8.0 you'd need to modify the function `authValidateUser()` in auth/auth_ldap.inc and at line 465 add

~~~php
  $user = utf8_strtolower($user);
~~~

However I'm slightly surprised by this because I thought LDAP was case-insensitive.  But I don't have access to an LDAP system at the moment to check.

**Comment by embeh** [comment]
Thanks!

This might be handled differently by various systems, ours implements OpenLDAP, and yesterday a user could not log into MRBS because he always wrote his username with first letter in uppercase. And I just tested it with my own account: all lowercase works, first letter in uppercase produces 'Unknown user or password'
