### ISSUE TITLE
$vocab_override["da"]["fulldescription"]  in config.inc.php

### ISSUE THREAD

**Issue by bks0401** [meeting-room-booking-system/mrbs-code#3534]
**Describe the problem you're facing/question you have**

I have added this to the config.inc.php.

~~~php
$vocab_override["da"]["fulldescription"] = "Contact details<br>Name:<br>Tel.:<br>Mail:";
~~~

In version 1.9.2 it works fine. It writes it as 3 lines in the online version (se below)

Contact details
Name:
Tel.:
Mail:

But when adding the same in version 1.11.0 it just writes it as one line in the online version. (see below)

~~~text
Contact details<br>Name:<br>Tel.:<br>Mail:
~~~

Is it possible to make it as 3 lines in version 1.11.0 and if yes so how ?

thanks in advance :-)

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Server details (please complete the following information):**
 - MRBS version 1.9.2 (works) 1.11.0 (not working)
 - Web server: Linux
 - OS: Litespeed
 - PHP version: 8.0.29
 - Database used: MySQL 10.3.39

**Additional context**

**Comment by campbell-m** [comment]
If you're running MRBS 1.11.0 you need to edit the function `get_field_entry_input()` in the file functions.inc and change line 2615 from

~~~php
  $field->setLabel($params['label'])
~~~

to

~~~php
  $field->setLabel($params['label'], false, true)
~~~

See also Issues #3007 

But you might be better off defing three custom fields, eg 'contact_name', 'contact_tel' and 'contact_mail' so that each field has its own input.  You then wouldn't need line breaks and furthermore these fields would show up as separate columns in reports, enabling you to analyse usage more easily.
