### ISSUE TITLE
Bulk import users

### ISSUE THREAD

**Issue by newtonpal** [meeting-room-booking-system/mrbs-code#3540]
I tried to insert a user using an SQL command. There is an error in the password field.

**_INSERT INTO mrbs_users (level, name, display_name, password, email)
VALUES ('1', 'reserva', 'Reserva EQUIP', '12_34_56', '[something@isp.org](mailto:something@isp.org)');

https://github.com/meeting-room-booking-system/mrbs-code/issues/1054 - Coluna 'password' desconhecida em 'field list'

How can I overcome?
Thank you for the patience

**Comment by campbell-m** [comment]
That's because there isn't a field called 'password'.  It's called 'password_hash' and contains the result of the PHP function `password_hash()`.

It might be easier not to try and set a password at all and leave out that column.  The user can then set their own password by following the "Lost your password?" link.

**Comment by newtonpal** [comment]
Thanls @campbell-m 
I had already thought about this solution, however, I will have to solve the SMTP problem. Not sending emails
