### ISSUE TITLE
Problem with Login after updating Joomla to Version 4.4

### ISSUE THREAD

**Issue by VCKHorst** [meeting-room-booking-system/mrbs-code#3547]
Hello.

We run MRBS under a Joomla webside.
So far Login into MRBS had worked from both sides - either Login into Joomla and then opened MRBS, or from MRBS and the logged in there.

Now, we have upgraded Joomla to version 4.4 and cannot login from MRBS side into MRBS.
We receive message after login screen is send:
"Oh je! Leider ist in MRBS ein schwerwiegender Fehler aufgetreten. Bitte konsultieren Sie Ihren Systemadministrator."
The Login works still ok when loggin to joomla and than call mrbs from there.

Problem occurs under Windows 10, with Firefox as well as MS Edge.
Please help.
Thanks and regards Horst Becker

**Comment by campbell-m** [comment]
Which version of MRBS are you running?

**Comment by campbell-m** [comment]
I have just tested against Joomla 4.4.  MRBS 1.11.4 fails as you say, but the latest code in the main branch works (I suspect due to the fixes in [80f4640](https://github.com/meeting-room-booking-system/mrbs-code/commit/80f4640b072b3060787db4309219db8791db5213)).  Can you upgrade to the latest development code which you can download by following the green Code button on [this page](https://github.com/meeting-room-booking-system/mrbs-code).  Treat it like a new release.

**Comment by VCKHorst** [comment]
Thank you campbell - I downloaded and copied the new code for mrbs (of Folder "web") and it is back to work again.
Thanks so much for the fast support.
Regrds

**Comment by campbell-m** [comment]
I have tested against Joomla 5.0.0 and found that there were issues there which are now fixed in [6937eb1](https://github.com/meeting-room-booking-system/mrbs-code/commit/6937eb16fd0de3f903382571abc1eae8f8e3f03d).

**Comment by VCKHorst** [comment]
Thanks I will have this in mind.

 

By the way – after the update the mails send to webmaster show English Time standards i.e  PM AM not 24 hrs anymore.

I have this in the config .php ,

 

/************************

* Miscellaneous settings

************************/

 

$strftime_format['datetime24'] = '%d.%m.%Y %H:%M:%S'; 

 

 

wondering where this AM PM comes from.

 

Thanks

 

 

Von: campbell-m ***@***.***> 
Gesendet: Montag, 30. Oktober 2023 18:53
An: meeting-room-booking-system/mrbs-code ***@***.***>
Cc: VCKHorst ***@***.***>; State change ***@***.***>
Betreff: Re: [meeting-room-booking-system/mrbs-code] Problem with Login after updating Joomla to Version 4.4 (Issue #3547)

 

I have tested against Joomla 5.0.0 and found that there were issues there which are now fixed in 6937eb1 <https://github.com/meeting-room-booking-system/mrbs-code/commit/6937eb16fd0de3f903382571abc1eae8f8e3f03d> .

**Comment by campbell-m** [comment]
Ah, this looks like a bug and I have raised it as a separate issue in #3550 .

In MRBS 1.11.4 the `$strftime_format` and `$twentyfourhour_format` config settings are redundant and have been replaced by the `$datetime_format` settings.  MRBS now tries to use PHP's Intl extension if possible, instead of `strftime()` which has been deprecated since PHP 8.1.  The Intl extension also offers better localisation.  [Your PHP error log will also be filling up with lots of notices about `$strftime_format` and `$twentyfourhour_format`.]

However there is a bug in the mail language settings.  I suspect you have the default setting of `$mail_settings['admin_lang'] = 'en';`?  I will fix the bug in the next few days.  In the meantime if you want to restore 24-hour times in your emails you can temporarily get round the bug by setting `$mail_settings['admin_lang'] = 'en-gb';` and copying the file 'lang.en' to 'lang.en-gb'.

**Comment by campbell-m** [comment]
I have now fixed [that bug](https://github.com/meeting-room-booking-system/mrbs-code/issues/3550).  If you download the latest code and set

`$mail_settings['admin_lang'] = 'en-GB';`

you should get times in 24 hour format.

**Comment by VCKHorst** [comment]
Thanks – I added it as

 

$mail_settings['admin_lang'] = 'de-DE';

 

Which worked too.

Regrds

 

Von: campbell-m ***@***.***> 
Gesendet: Donnerstag, 2. November 2023 18:41
An: meeting-room-booking-system/mrbs-code ***@***.***>
Cc: VCKHorst ***@***.***>; State change ***@***.***>
Betreff: Re: [meeting-room-booking-system/mrbs-code] Problem with Login after updating Joomla to Version 4.4 (Issue #3547)

 

I have now fixed that bug <https://github.com/meeting-room-booking-system/mrbs-code/issues/3550> . If you download the latest code and set

$mail_settings['admin_lang'] = 'en-GB';

you should get times in 24 hour format.
