### ISSUE TITLE
Current date highlighted

### ISSUE THREAD

**Issue by lagethomas** [meeting-room-booking-system/mrbs-code#3564]
I think it would be interesting for the current date to be highlighted in the calendar when you open it.
An example is the GLPI calendar.

![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/47001888/82a45057-cff0-4079-ae3b-7cf206e6d085)

**Comment by campbell-m** [comment]
What does it look like on the week view?  And on the day view if the day is today?

**Comment by lagethomas** [comment]
> What does it look like on the week view? And on the day view if the day is today?

you mean in GLPI?

**Comment by lagethomas** [comment]
In GLPi the view is like this and there is a list option too.
But GLPI is an IT ticket and asset management system. But even before I discovered MRBS, I used it adapted to reserve rooms.
MRBS is very good.

![U
![lista_glpi](https://github.com/meeting-room-booking-system/mrbs-code/assets/47001888/dbfe47b7-464c-476f-a1ce-a13b228b9691)
![semana_glpi](https://github.com/meeting-room-booking-system/mrbs-code/assets/47001888/bb98ff85-94c4-4eee-8a66-e09169e5acb5)
ploading dia_glpi.png…]()

**Comment by campbell-m** [comment]
Thanks.

**Comment by campbell-m** [comment]
I've now ([4391d6f](https://github.com/meeting-room-booking-system/mrbs-code/commit/4391d6f153588eeb5bfa7f939e8756e8995dd4a1)) added a class of "today" to the `<td>` cells if it's the current date.  I haven't added any styling, but you can add your own styling by creting a custom CSS file and add a rule such as

~~~css
.dwm_main#month_main:not(.all_rooms) .today {
  box-shadow: inset 0 0 0 1px #aaaaaa;  /* adds an outline */
}
~~~

or

~~~css
.dwm_main#month_main:not(.all_rooms) .today {
  background-color: #aaaaaa;
}
~~~

The reason I haven't added any styling yet is because it's a bit tricky.  Background colours are already used to denote weekends and holidays.  Adding a third background colour might be confusing, especially if he current date is a weekend or a holiday.  Instead I thought changing the border, eg making it darker, could be a way to do denote the current day.  But this is a bit tricky to achieve, either using `border-collapse: separate`, which is the mode at the moment, or `border-collapse: collapse`.  If the borders are collapsed then one also has to think about the JavaScript code which resizes bookings in the day and week views.  The box-shadow solution above is relative simple but not ideal, as it is hidden by entries.  I might come back to it some other time.

**Comment by lagethomas** [comment]
> Agora ( [4391d6f](https://github.com/meeting-room-booking-system/mrbs-code/commit/4391d6f153588eeb5bfa7f939e8756e8995dd4a1) ) adicionei uma classe "hoje" às `<td>`​​células se para os dados atuais. Não adicionei nenhum estilo, mas você pode adicionar seu próprio estilo criando um arquivo CSS personalizado e adicionando uma regra como
> 
> ```css
> .dwm_main#month_main:not(.all_rooms) .today {
>   box-shadow: inset 0 0 0 1px #aaaaaa;  /* adds an outline */
> }
> ```
> 
> ou
> 
> ```css
> .dwm_main#month_main:not(.all_rooms) .today {
>   background-color: #aaaaaa;
> }
> ```
> 
> A razão pela qual ainda não adicionei nenhum estilo é porque é um pouco complicado. Os núcleos de fundo já são usados ​​para indicar fins de semana e feriados. Adicionar uma terceira parte do fundo pode ser confuso, especialmente se os dados atuais também forem para um fim de semana ou feriado. Em vez disso, pensei que mudar a borda, por exemplo, tornando-la mais escura, poderia ser uma forma de indicar o dia atual. Mas isso é um pouco complicado de conseguir, seja usando `border-collapse: separate`, que é o modo no momento, ou `border-collapse: collapse`. Se as fronteiras forem diminutas, também será necessário pensar no código JavaScript que redimensiona as reservas nas visualizações diárias e semanais. A solução box-shadow acima é relativamente simples, mas não é a ideal, pois está oculta por entradas. Talvez eu volte a fazer isso em outra hora.

Main. I followed what was changed and it worked, I set the border as a highlight.

![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/47001888/ac3fdd94-9af6-4926-91c7-43bb98c46368)
