### ISSUE TITLE
Can I add custom fields in Entry and Repeat table to several specific rooms? (Not all rooms)

### ISSUE THREAD

**Issue by fuzezeze** [meeting-room-booking-system/mrbs-code#3584]
We want to add a "Do you need IT support" custom field to the entry and repeat. So that the user will need to answer this when booking. But we hope only several rooms enable this field. Can this be done by adding columns in MyPHpAdmin? 

MRBS 1.6.1 

Thanks a lot for the help.

**Comment by campbell-m** [comment]
No, this isn't possible as standard. You'd need to modify the code in edit_entry.php and possibly edit_entry_handler.

**Comment by campbell-m** [comment]
It would also get complicated with the JavaScript.  You'd need to modify the code in js/edit_entry,js.php so that when the room selection changes the custom fields are shown or hidden as appropriate.  And then you'd need to think about the case when somebody selects two rooms, one of which allows the custom fields and the other doesn't.

Altogether it would be quite complicated.

**Comment by fuzezeze** [comment]
Thanks Campbell
