### ISSUE TITLE
the language of the web page

### ISSUE THREAD

**Issue by bahijamahfoud** [meeting-room-booking-system/mrbs-code#3652]
I can't set the language for the MRBS web page.

I have a mix of languages, some sentences in French and others in English.

Can you help me please ?

**Comment by campbell-m** [comment]
Yes, it's because there isn't a French translation for the 'ignore_location' token.  To fix this for your site you can add to your config file:

~~~php
$vocab_override['fr']['ignore_location'] = "Use the default room instead of LOCATION";  // Translate into French
~~~

If you find other English strings, then search for that string in lang/lang.en, note the token and add an override to your config file.

If your translations are of general use and not site specific, then you could always submit a PR.  See also the checklang.php utiity in the MRBS distribution which can be run on your server in the same directory that your config file is in.

**Comment by bahijamahfoud** [comment]
I only have it in these lines, it’s weird isn’t it? 
![Capture](https://github.com/meeting-room-booking-system/mrbs-code/assets/43571015/11201086-650f-4f26-b084-c11661252830)

**Comment by bahijamahfoud** [comment]
I added the line that you recommended in my config.ini.php file but nothing has changed

**Comment by campbell-m** [comment]
> I only have it in these lines, it’s weird isn’t it?

That's because those are the tokens that don't have a French translation yet.
