### ISSUE TITLE
Error message when displaying a reservation

### ISSUE THREAD

**Issue by bahijamahfoud** [meeting-room-booking-system/mrbs-code#3656]
I migrated data from an old MRBS database to a new MRBS database.
when I click on a reservation to get the details, I get this error message that appears :  **Oops ! Unfortunately, MRBS encountered a fatal error. Please inform your system administrator.**

the same error message when I want to display a report on reservations.

Can you help me please?

Thanks in advance

**Comment by campbell-m** [comment]
How did you perform the migration?  What were the two versions of MRBS?  What is the detailed error message in your PHP error log?

**Comment by bahijamahfoud** [comment]
I carried out the migration by creating a table that I named entry in the new database with the same data types as the table in the old database, then I made a request to copy the table that I created towards the mrbs_entry table.

the versions of the two MRBS: the old MRBS is version (1.4.4.1), the new mrbs is version (1.11.4-1) in docker.

I don't know how I can find the PHP error log

**Comment by campbell-m** [comment]
To do the migration you should export _all_ the tables from your old database and import them into your new database, changing the table prefix (which is by default '_mrbs') if necessary.  When you first run MRBS against the new database it will prompt you for  a database username and password so that it can automatically upgrade the database structure.

**Comment by bahijamahfoud** [comment]
thank you for your reply.
how I can export all tables from the old database and import them into the new database?

**Comment by campbell-m** [comment]
You could use something like phpMyAdmin.
