### ISSUE TITLE
Multiple way to login

### ISSUE THREAD

**Issue by Metz01** [meeting-room-booking-system/mrbs-code#3660]
Hi, I've had a recent request about a feature to add to the mrbs app and I was wondering if there is already a quite easy solution at this. The problem is that I've implemented the login via `saml` and the `$auth['deny_public_access'] = TRUE;` and so no one could enter the calendar without a personal account registered in the idp of the organization. But now we figured out there is a person outside the organization who need to have access at the calendar. Being outside the organization he doesn't have a mail to login via saml so I need a new way for him to login.

**So the question is, is there a way to have two different login type?**

I saw there is a similar thread but it doesn't actually answer my question completely, or at least I'm confused in some parts. The usernames in the non-saml login will be unique. I saw it was suggested to create a new class like `AuthDbSaml` or `AuthldapSaml`, (and I think in the config set `$auth["type"]="dbsaml"`?) but then how can I make the user choose which login to use? Isn't the Auth file just to set the info of the user after the login?

Thank you for the support as always

**Comment by campbell-m** [comment]
It's not quite that simple.  Yes, using Saml the Auth class just validates the user and gets their details.  But there's also the Session class which gets details of the currently logged on user.  So you'd have to extend both the Auth and Session classes to cater for the two authentication types.

**Comment by Metz01** [comment]
The problem is that now, when I enter the page, I'm redirected to the saml authentication. Where can I specify to bring me to the page where a user can choose with which authentication method to log in?

**Comment by Metz01** [comment]
Sorry to bother you again @campbell-m but I'm kinda stuck in trying to understand what happens. I just need to know what happens when you are redirected to the login page having  `$auth['deny_public_access'] = TRUE;`. Where is the code that says "go to that page for the login" and where is that page? I can't figure out how to add a new custom page for the login where a user can choose which login to use and then be redirected to the chosen login page

**Comment by campbell-m** [comment]
The code that triggers the login is the `authGet()` method in the Session classes.  I haven't quite figured out how to solve your problem.  It might be possible to have a form that allows the user to choose their authentication type and then somehow store that choice somehere, perhaps in a PHP session variable, and then clear that choice on logout.

One thing to think about is the `getUserFresh()` method in the Auth classes.  This gets the details, eg display name and email address, of other users band is used, for example, when displaying the bookings of other users.  I suppose that if your usernames are unique across the two methods then you could try one authentication type and then the other when searching for a user.  (For a more general solution perhaps a user id, rather than a username, would have to be associated with an entry and the user table would have to store the authentication type.  But that woukd be a major change.)

**Comment by campbell-m** [comment]
Another way of solving the problem would be to have two installations of MRBS (or better, use the multisite option so that you just have one set of code files but two config files) with each configured to use different authentication methods, but the same database tables.  Then the choice as to which authentication method you use is made by which site you point your browser at.

You'd still have to solve the `getUserFresh()` problem above - unless you are happy just to see usernames rather than display names for users from the other authentication type.

Overall I think this solution woulkd be a lot cleaner and simpler to implement.

**Comment by Metz01** [comment]
The 

> Another way of solving the problem would be to have two installations of MRBS (or better, use the multisite option so that you just have one set of code files but two config files) with each configured to use different authentication methods, but the same database tables. Then the choice as to which authentication method you use is made by which site you point your browser at.
> 
> You'd still have to solve the `getUserFresh()` problem above - unless you are happy just to see usernames rather than display names for users from the other authentication type.
> 
> Overall I think this solution would be a lot cleaner and simpler to implement.

The multisite is enough, so I started trying to implement it, but I encountered a new error:
`MRBS configuration error: MRBS\Session\SessionSaml needs $auth['type'] set to 'saml'`
I have `$multiste=true` and `$default='external'`, the external has a saml authentication and I have another site with a ldap autenthication.

**Comment by campbell-m** [comment]
If you're using SAML authentication then both `$auth['type']` and `$auth['session']` should be set to 'saml'.   You should have this in the external config file, eg 'sites/external/config.inc.php', and then in the config file for the ldap site, eg 'sites/ldap/config.inc.php' you should have

~~~php
$auth['type'] = 'ldap';
$auth['session'] = 'php';
~~~

Then if you want SAML authentication you go to index.php?site=external (or just index.php) and for LDAP authentication index.php?site=ldap.

**Comment by Metz01** [comment]
RIght, that was the problem. Fixed it and now it's working fine. Thanks!
