### ISSUE TITLE
mrbs_sessions table

### ISSUE THREAD

**Issue by sixsax** [meeting-room-booking-system/mrbs-code#3721]
can I empty the sessions table manually?

**Comment by campbell-m** [comment]
Yes, you can.  If you do so it's best to delete the rows with the lowest access values first, to avoid logging out users.

If your sessions table keeps filling up then check your php.ini file and make sure you have the three `session.gc_*` variables set appropriately. The garbage collector should automatically prune your sessions table from time to time.

**Comment by mi-dave** [comment]
> If your sessions table keeps filling up then check your php.ini file and make sure you have the three `session.gc_*` variables set appropriately. The garbage collector should automatically prune your sessions table from time to time.

Thanks for the pointer.

For anyone with a similar issue - I discovered that Debian/Ubuntu [disable garbage collection by default](https://serverfault.com/q/511609) and use a cron job instead... But the cron job doesn't work for MRBS because it uses a custom session handler. I added this to `web/.user.ini` to re-enable it just for MRBS:

```ini
session.gc_probability = 1
session.gc_divisor = 100
```

**Comment by campbell-m** [comment]
I wonder whether it would be useful for MRBS to set these at runtime using `ini_set()`?  The config file could contain the values.  If they were not set - and this could be the default to avoid upsetting existing sites? - then MRBS wouldn't do anything.

**Comment by mi-dave** [comment]
Sounds sensible to me. 🙂
