### ISSUE TITLE
Room Owner Features

### ISSUE THREAD

**Issue by akramjannah** [meeting-room-booking-system/mrbs-code#3781]
Sorry to ask, i want to know if this system have fuction only room owner can book or manage the room, i try to find config but not found it

**Comment by campbell-m** [comment]
No, there isn't a configuration option.  The room_admin is badly named: it's just someone who receives notifications about room bookings.

To do what you want you would need to edit the MRBS code, in particular mrbs_auth.inc.

Alternatively you could use the [roles branch](https://github.com/meeting-room-booking-system/mrbs-code/tree/roles).  But that code (a) is still under development and (b) will ugrade your database so that it is no longer compatible with MRBS 1.11.6.  So if you choose to go down that route I recommend you set up a test installation first.
