### ISSUE TITLE
booking confirmation emails

### ISSUE THREAD

**Issue by kalacho** [meeting-room-booking-system/mrbs-code#3794]
**Describe the problem you're facing/question you have**
We use MRBS for many years but never activated the booking confirmation emails. Sorry for my ignorance but are there directions on how to activate them (so I could share that info with our IT department)? And I assume the template can be edited, right? If not, could someone please share how the default email looks like? We mostly want to confirm that it includes the area name and room number.

**Comment by sjzbim** [comment]
I tried many times to set up SMTP , fail all the time , I have the same question with you. Could someone please share how the default email looks like?  Thanks a lot !

**Comment by campbell-m** [comment]
Here's a sample email:

![Email_sample](https://github.com/user-attachments/assets/415760f8-7c66-4c6b-8780-b39e67c637f2)

It also can have a .ics attachment so that it can be entered into your calendar.

To configure email see the section on "Email settings" in systemdefaults.inc.php.  If you are having trouble, turn on the debug setting.

**Comment by kalacho** [comment]
Thanks a lot for sharing the template. It looks like the "Area" is not included. Is it possible to add it?

**Comment by campbell-m** [comment]
The area is included. In the example above the area is "Cities" and the room is "Paris".

**Comment by kalacho** [comment]
Ah, excellent. Sorry, I didn't realize that was the area name. Thanks a lot for the clarification.
