### ISSUE TITLE
referrer Problem when use strict header Referrer-Policy

### ISSUE THREAD

**Issue by ger82** [meeting-room-booking-system/mrbs-code#57]
When I use
Header set Referrer-Policy: strict-origin
on apache2 config.
Then only https://example.com will used as returl in view_entry.php.
So if you delete an entry you will redirected to https://example.com and not to https://example.com/mrbs where mrbs is installed.
I think it is better to use $url_base form config.inc.php as Fallback.

An other solution is to use Header set Referrer-Policy: same-origin but sometimes you can't change this.

**Comment by campbell-m** [comment]
OK, I'll take a look.

**Comment by campbell-m** [comment]
I've created a [pull request](https://github.com/meeting-room-booking-system/mrbs-code/pull/58) to address this issue.

Rather than use `$url_base` which won't have the query string data, I've stored the last page as a session variable to use instead of `$_SERVER['HTTP_REFERER']` if HTTP_REFERER is set.  This technique has the disadvantage that it only works when using PHP sessions, but that is the most common case.
